// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiwmtxeqkmwiuxmfucfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpd210eGVxa213aXV4bWZ1Y2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzExMzcsImV4cCI6MjA2MDQ0NzEzN30.nobbY275Zxj-e-VNeti7-ehdTlqS31kp_MxZ6ZtihT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);