// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyiyuiuewnxlsguiqzsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aXl1aXVld254bHNndWlxenNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjU0ODcsImV4cCI6MjA2MDQ0MTQ4N30.dcavE_lkxCXQdJdCyIu0UkDtQ-D7cOhZY8GGojyEqOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);